### ISSUE TITLE
kobs 4.0.0 and 5.5 can't handle NAND with 2048 page/128 oob

### ISSUE THREAD

**Issue by dangerousHobo** [NXPmicro/imx-kobs#21]
I'm using the following Cypress 8Gbit NAND with kobs 4.0.0 on linux 2.6.35 (imx53 custom pcb). When using kobs to flash u-boot I get an 'unsupported geometry' error message. Looking at mtd.c(mtd_open), I see no entry for a write/oob size of 2048/128, so I added one. This got me past the errors but now kobs reports ECC strength of 18. This section of the code looks the same between release 4.0.0 and 5.5. I'm I missing something trying to add support for my NAND's geometry?

**Comment by allenxh** [comment]
Hi, i.MX53 uses different NAND controller called NFC. kobs-ng was designed to support GPMI/BCH NAND controller, which cannot support i.MX53. Please look for "ATK tool" to burn NAND for i.MX53.

**Comment by dangerousHobo** [comment]
Thanks, I'll look into this.
